const cardImages = [
    {
        id: 0,
        image: `/images/recipe-app/recipe-app--1.png`,
        title: 'Recipe Application',
        date: 'Oktober 2021',
        githubLink: 'https://github.com/AleksandarIlicc/recipe-app',
        netlifyLink: 'https://react-restaurant-application.netlify.app',
    },
    {
        id: 1,
        image: `/images/portfolio/portfolio--1.png`,
        title: 'Portfolio Website',
        date: 'Oktober 2021',
        githubLink: 'https://github.com/AleksandarIlicc/portfolio-aitana',
        netlifyLink: 'https://aitana-portfolio.netlify.app',
    },
    {
        id: 2,
        image: '/images/components/react-form-validation--1.png',
        title: 'React From Validation',
        date: 'Oktober 2021',
        githubLink: 'https://github.com/AleksandarIlicc/neumorphic-login-form-',
        netlifyLink: 'https://glassmorphism-form.netlify.app',
    },
    {
        id: 3,
        image: `/images/building app/building-app--1.png`,
        title: 'Building Website',
        date: 'November 2021',
        githubLink: 'https://github.com/AleksandarIlicc/building-website',
        netlifyLink: 'https://building-app.netlify.app',
    },
    {
        id: 4,
        image: '/images/components/slider--1.png',
        title: 'Slider component',
        date: 'November 2021',
        githubLink: 'https://github.com/AleksandarIlicc/javascript-image-slider',
        netlifyLink: 'https://images-slider-js.netlify.app',
    },
    {
        id: 5,
        image: '/images/components/accordion--1.png',
        title: 'Accordion component',
        date: 'November 2021',
        githubLink: 'https://github.com/AleksandarIlicc/accordion',
        netlifyLink: 'https://accordion-js-css.netlify.app',
    },
    {
        id: 6,
        image: '/images/components/animated-card--1.png',
        title: 'Animated Card component',
        date: 'November 2021',
        githubLink: 'https://github.com/AleksandarIlicc/animated-card',
        netlifyLink: 'https://fancy-css-animated-card.netlify.app/',
    },
    {
        id: 7,
        image: '/images/components/todo--1.png',
        title: 'ToDo List component',
        date: 'December 2021',
        githubLink: 'https://github.com/AleksandarIlicc/javascript-todo-list',
        netlifyLink: 'https://vanilla-js-todo-application.netlify.app',
    },
    {
        id: 8,
        image: '/images/components/travel-card--1.png',
        title: 'Travel Card component',
        date: 'December 2021',
        githubLink: 'https://github.com/AleksandarIlicc/css-travel-card',
        netlifyLink: 'https://travel-card.netlify.app',
    },
    {
        id: 9,
        image: '/images/post-app/react-post--1.png',
        title: 'React Post App',
        date: 'January 2022',
        githubLink: 'https://github.com/AleksandarIlicc/react-post-app',
        netlifyLink: 'https://react-post-application.netlify.app',
    },
    {
        id: 10,
        image: '/images/restaurant-app/restaurant--1.png',
        title: 'Restaurant App',
        date: 'April 2022',
        githubLink: 'https://github.com/AleksandarIlicc/react-restaurant-app',
        netlifyLink: 'https://react-restaurant-application.netlify.app',
    }
]

export default cardImages;